Repository Shepe1304/odyscribe, pull requests merged in 2025-07, with the labels that each got.

#4 frontend - enhancement: Styled the login and signup forms
  app/auth/login/page.tsx
  app/auth/sign-up/page.tsx
  app/layout.tsx
  components/login-form.tsx
  components/sign-up-form.tsx
Labels: Review effort 3/5

#7 feat: new entry creation with markdown
  app/entry/[id]/page.tsx
  app/entry/new/page.tsx
Labels: Review effort 4/5, Possible security concern

#8 feat: generate chapter UI with mock data, not yet factored/structured…
  app/chapter/generate/page.tsx
Labels: enhancement, Review effort 3/5, Possible security concern

#9 feat: storybook view with mock data, not yet refactored/structured code
  app/chapter/[id]/page.tsx
  app/storybook/loading.tsx
  app/storybook/page.tsx
  components/narration-player.tsx
Labels: Review effort 3/5

#10 enhancement: extracted reusable header, changed screen flow from the …
  app/chapter/[id]/page.tsx
  app/dashboard/page.tsx
  app/entry/[id]/page.tsx
  app/entry/new/page.tsx
  app/layout.tsx
  app/onboarding/page.tsx
  app/page.tsx
  app/storybook/page.tsx
  components/global-header.tsx
  components/login-form.tsx
  components/protected-layout.tsx
  public/placeholder.svg
Labels: Review effort 4/5

#11 feat: added write/edit functionality for entries
  app/entry/[id]/page.tsx
  app/entry/new/page.tsx
  app/storybook/page.tsx
Labels: Review effort 4/5, Possible security concern

#12 chore: fix redirect bug
  components/login-form.tsx
Labels: Review effort 2/5

#13 chore: fixed redirect bug
  components/global-header.tsx
  components/login-form.tsx
Labels: Review effort 2/5

#14 Enhancement/ux
  app/landing/page.tsx
  app/page.tsx
  components/protected-layout.tsx
Labels: Review effort 3/5

#16 feat: ai generation, as well as minor tweaks
  .env.example
  app/api/generate-chapter/route.ts
  app/chapter/[id]/page.tsx
  app/chapter/generate/onboarding/page.tsx
  app/chapter/generate/page.tsx
  app/chapter/generate/preview/page.tsx
  app/dashboard/page.tsx
  app/entry/[id]/page.tsx
  app/layout.tsx
  app/storybook/page.tsx
  next.config.ts
  package-lock.json
  package.json
Labels: Review effort 4/5, Possible security concern

#17 Feat/ai generation
  app/dashboard/page.tsx
  app/storybook/page.tsx
  components/global-header.tsx
Labels: Review effort 4/5

#18 feat: added user profile and chapter timeline
  app/api/generate-chapter/route.ts
  app/profile/page.tsx
  components/global-header.tsx
Labels: Review effort 4/5

#19 feat: Add TTS from ElevenLabs' API
  components/narration-player.tsx
Labels: Review effort 3/5

#20 enhancement: code cleanup, temporarily disable dark/light mode
  app/instruments/page.tsx
  app/layout.tsx
  app/protected/layout.tsx
Labels: Review effort 2/5

#24 enhancement: replaced alerts with sonner toast notifications, updated…
  README.md
  app/chapter/[id]/page.tsx
  app/chapter/generate/onboarding/page.tsx
  app/chapter/generate/preview/page.tsx
  app/entry/[id]/page.tsx
  app/entry/new/page.tsx
  app/layout.tsx
  app/storybook/page.tsx
  package-lock.json
  package.json
Labels: Review effort 2/5

#26 enhancement: final touches 2
  app/profile/page.tsx
  components/narration-player.tsx
Labels: Review effort 3/5

#29 fix: fix for demo deployment (does not change any business logic), co…
  app/protected/layout.tsx
  app/protected/page.tsx
  components/sign-up-form.tsx
  components/update-password-form.tsx
Labels: Review effort 2/5, Possible security concern
